# Generated by Django 4.2.3 on 2023-10-18 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("actor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("last_update", models.DateTimeField()),
            ],
            options={
                "db_table": "actor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("last_update", models.DateTimeField()),
            ],
            options={
                "db_table": "category",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                ("film_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("rental_duration", models.SmallIntegerField()),
                ("rental_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                ("length", models.SmallIntegerField(blank=True, null=True)),
                (
                    "replacement_cost",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("rating", models.TextField(blank=True, null=True)),
                ("last_update", models.DateTimeField()),
                ("special_features", models.TextField(blank=True, null=True)),
                ("fulltext", models.TextField()),
            ],
            options={
                "db_table": "film",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("language_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("last_update", models.DateTimeField()),
            ],
            options={
                "db_table": "language",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FilmActor",
            fields=[
                (
                    "actor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="filmApp.actor",
                    ),
                ),
                ("last_update", models.DateTimeField()),
            ],
            options={
                "db_table": "film_actor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FilmCategory",
            fields=[
                (
                    "film",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="filmApp.film",
                    ),
                ),
                ("last_update", models.DateTimeField()),
            ],
            options={
                "db_table": "film_category",
                "managed": False,
            },
        ),
    ]
