# Generated by Django 4.2.3 on 2023-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmApp", "0002_address_city_country_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todos",
            fields=[
                ("todo_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("completed", models.DateTimeField()),
            ],
            options={
                "db_table": "todos",
                "managed": False,
            },
        ),
    ]
