# Generated by Django 4.2.2 on 2023-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jointable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("city", models.CharField(max_length=255)),
            ],
        ),
    ]
